### ISSUE TITLE
Add abstracts for your links?

### ISSUE THREAD

**Issue by beyondpie** [noffle/wisdom#1]
Hi, 
Nice to see your wisdom after reading your art-of-readme. 
How about add your personal abstracts for the links in your documents instead of just giving the links? (1. the link might not work in the future; 2. read the abstract, then determine click or not the links?)
Songpeng

**Comment by hackergrrl** [comment]
Hi @songpeng, I think that's a great idea. :+1: 

We'll see whether I find the time to sit down and write my own abstracts (I wouldn't hold my breath :grinning:). Perhaps I'll try this for future articles!

As for the broken link problem, I've been considering hosting mirrors of these on [IPFS](https://ipfs.io) to ensure they stick around longer. Thanks!

**Comment by beyondpie** [comment]
Thanks. Yes, time is limited~ 
BTW,  how about put the section _node&javascripts_ behind that of _the unix way_, or _open source community_ ? I think the latter is more general topic.
Any way, thanks a lot for your sharing~
Songpeng
